<?php
/**
 * Pedima Enterprises — site content
 * Update this file to change copy, services, WhatsApp numbers, and Instagram posts.
 * Only include facts verified from https://www.instagram.com/pedima_enterprises/
 */
return [
    'company' => 'Pedima Enterprises',
    'handle' => 'pedima_enterprises',
    'instagram' => 'https://www.instagram.com/pedima_enterprises/',
    'site_url' => 'https://www.pedima.co.tz',
    'listed_website' => 'www.pedima.co.tz',

    'whatsapp_primary' => '255613100100',
    'whatsapp_primary_display' => '0613 100 100',

    'address_name' => 'Pedima Enterprises',
    'address_line' => 'Tegeta Kibaoni, Bagamoyo Rd',
    'address_city' => 'Dar es Salaam',
    'address_country' => 'Tanzania',
    'address_display_sw' => 'Tegeta Kibaoni, Bagamoyo Rd, Dar es Salaam',
    'address_display_en' => 'Tegeta Kibaoni, Bagamoyo Rd, Dar es Salaam',
    'geo_lat' => '-6.6625582',
    'geo_lng' => '39.1853593',
    'maps_place' => 'https://www.google.com/maps/place/Pedima+enterprises/@-6.6625582,39.1853593,17z/data=!3m1!4b1!4m6!3m5!1s0x185c57748c3f64c3:0x58463c87c4ca0062!8m2!3d-6.6625582!4d39.1853593',
    'maps_embed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3979.2!2d39.1853593!3d-6.6625582!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c57748c3f64c3%3A0x58463c87c4ca0062!2sPedima%20enterprises!5e0!3m2!1sen!2stz!4v1724560000000!5m2!1sen!2stz',
    'maps_directions' => 'https://www.google.com/maps/dir/?api=1&destination=Pedima+enterprises,+Tegeta+Kibaoni,+Bagamoyo+Rd,+Dar+es+Salaam',

    'brands' => [
        'mpesa' => [
            'id' => 'mpesa',
            'name' => 'M-Pesa',
            'logo' => 'assets/logos/mpesa.png',
            'alt' => 'M-Pesa',
            'shape' => 'stacked',
            'width' => 88,
            'height' => 76,
        ],
        'airtel' => [
            'id' => 'airtel',
            'name' => 'Airtel Money',
            'logo' => 'assets/logos/airtel-money.png',
            'alt' => 'Airtel Money',
            'shape' => 'wide',
            'width' => 140,
            'height' => 68,
        ],
        'tigo' => [
            'id' => 'tigo',
            'name' => 'Tigo Pesa',
            'logo' => 'assets/logos/tigo-pesa.png',
            'alt' => 'Tigo Pesa',
            'shape' => 'badge',
            'width' => 120,
            'height' => 72,
        ],
        'halotel' => [
            'id' => 'halotel',
            'name' => 'Halotel Money',
            'logo' => 'assets/logos/halopesa.png',
            'alt' => 'HaloPesa',
            'shape' => 'badge',
            'width' => 72,
            'height' => 72,
        ],
        'halopesa' => [
            'id' => 'halopesa',
            'name' => 'HaloPesa',
            'logo' => 'assets/logos/halopesa.png',
            'alt' => 'HaloPesa',
            'shape' => 'badge',
            'width' => 72,
            'height' => 72,
        ],
        'ttcl' => [
            'id' => 'ttcl',
            'name' => 'T-Pesa',
            'logo' => 'assets/logos/t-pesa.png',
            'alt' => 'TTCL T-Pesa',
            'shape' => 'wide',
            'width' => 140,
            'height' => 42,
        ],
        'zantel' => [
            'id' => 'zantel',
            'name' => 'Zantel ezyPESA',
            'logo' => 'assets/logos/zantel.png',
            'alt' => 'Zantel',
            'shape' => 'badge',
            'width' => 72,
            'height' => 72,
        ],
        'azampesa' => [
            'id' => 'azampesa',
            'name' => 'AzamPesa',
            'logo' => 'assets/logos/azampesa.png',
            'alt' => 'AzamPesa',
            'shape' => 'wide',
            'width' => 160,
            'height' => 44,
        ],
    ],
    'networks' => ['mpesa', 'airtel', 'tigo', 'halotel', 'ttcl', 'zantel'],

    'highlights' => ['AzamPesa Bure', 'HaloPesa Bure', 'M-Pesa Lipa', 'Tariffs'],

    'requirements' => [
        ['sw' => 'TIN Number', 'en' => 'TIN Number'],
        ['sw' => 'Kitambulisho cha Taifa (NIDA)', 'en' => 'National ID (NIDA)'],
        ['sw' => 'Namba / laini ya Halotel', 'en' => 'A Halotel number / line'],
    ],

    'services' => [
        [
            'id' => 'uwakala-halopesa',
            'icon' => 'shop',
            'image' => 'assets/images/team-halopesa.jpg',
            'logos' => ['halopesa'],
            'name_sw' => 'Uwakala wa HaloPesa',
            'name_en' => 'HaloPesa agent line',
            'desc_sw' => 'Pata uwakala wa HaloPesa. Pedima inasema huduma hii ni bure kabisa ndani ya masaa 24.',
            'desc_en' => 'Get a HaloPesa agent line. Pedima describes this service as completely free, within 24 hours.',
        ],
        [
            'id' => 'lipa-halopesa',
            'icon' => 'smartphone',
            'image' => 'assets/images/offer-halopesa.jpg',
            'logos' => ['halopesa'],
            'name_sw' => 'Lipa Namba ya HaloPesa',
            'name_en' => 'HaloPesa Lipa number',
            'desc_sw' => 'Lipa Namba ya HaloPesa kiganjani mwako — ikiwa una TIN, kitambulisho cha taifa, na namba ya Halotel.',
            'desc_en' => 'A HaloPesa Lipa number — if you have a TIN, national ID, and a Halotel number.',
        ],
        [
            'id' => 'lipa-mpesa',
            'icon' => 'smartphone',
            'image' => 'assets/images/hero-lipa.jpg',
            'logos' => ['mpesa'],
            'name_sw' => 'M-Pesa Lipa Namba',
            'name_en' => 'M-Pesa Lipa number',
            'desc_sw' => 'Pata Lipa Namba ya M-Pesa. Wasifu wa Pedima unaorodhesha M-Pesa Lipa kati ya huduma zao.',
            'desc_en' => 'Get an M-Pesa Lipa number. Pedima lists M-Pesa Lipa among its services.',
        ],
        [
            'id' => 'azampesa',
            'icon' => 'bank',
            'image' => 'assets/images/vibe.jpg',
            'logos' => ['azampesa'],
            'name_sw' => 'AzamPesa',
            'name_en' => 'AzamPesa',
            'desc_sw' => 'Line ya uwakala ya AzamPesa. Highlight ya Instagram inaitwa “AzamPesa Bure”.',
            'desc_en' => 'AzamPesa agent line. The Instagram highlight is titled “AzamPesa Bure”.',
        ],
        [
            'id' => 'airtel-voda',
            'icon' => 'smartphone',
            'image' => 'assets/images/vibe.jpg',
            'logos' => ['airtel', 'mpesa'],
            'name_sw' => 'Airtel Lipa na Lipa Voda',
            'name_en' => 'Airtel Lipa and Voda Lipa',
            'desc_sw' => 'Wasifu unaorodhesha Airtel Lipa. Graphic ya Disemba 2023 inaongeza “Lipa Voda & Airtel”.',
            'desc_en' => 'The profile lists Airtel Lipa. A December 2023 graphic also lists “Lipa Voda & Airtel”.',
        ],
        [
            'id' => 'points',
            'icon' => 'check',
            'image' => 'assets/images/points.jpg',
            'logos' => ['halopesa'],
            'name_sw' => 'Points za HaloPesa',
            'name_en' => 'HaloPesa points',
            'desc_sw' => '“Pata Points za HaloPesa Bureee.” Graphic inasema points za kutosha kila unapofanya miamala.',
            'desc_en' => '“Get HaloPesa points free.” The graphic says enough points every time you transact.',
        ],
    ],

    'updates' => [
        [
            'date' => '2025-09-14',
            'image' => 'assets/images/hero-lipa.jpg',
            'url' => 'https://www.instagram.com/p/DOmK5C3je-h/',
            'title_sw' => 'Lipa Namba na uwakala wa HaloPesa — bure',
            'title_en' => 'Lipa numbers and HaloPesa agency — free',
            'excerpt_sw' => 'Pata Lipa Namba ya M-Pesa, Lipa Namba ya HaloPesa na uwakala wa HaloPesa bure kabisa. Fursa kwa vijana kutengeneza Lipa Namba na uwakala nchi nzima.',
            'excerpt_en' => 'Get M-Pesa and HaloPesa Lipa numbers and HaloPesa agency, described as completely free. Youth can work with Pedima making Lipa numbers and agent lines nationwide.',
        ],
        [
            'date' => '2025-05-23',
            'image' => 'assets/images/team-halopesa.jpg',
            'url' => 'https://www.instagram.com/p/DJ_oribMtZH/',
            'title_sw' => 'Tupo tayari kukusajili haraka na urahisi',
            'title_en' => 'Ready to register you quickly and easily',
            'excerpt_sw' => 'Pata uwakala wa HaloPesa na Lipa Namba ya HaloPesa ndani ya masaa 24. Jiunge nasi leo.',
            'excerpt_en' => 'Get HaloPesa agency and a HaloPesa Lipa number within 24 hours. Join today.',
        ],
        [
            'date' => '2025-04-17',
            'image' => 'assets/images/offer-halopesa.jpg',
            'url' => 'https://www.instagram.com/p/DIiwoH2MWWQ/',
            'title_sw' => 'HaloPesa wakala na Lipa Namba — masaa 24 tu',
            'title_en' => 'HaloPesa agent and Lipa number — 24 hours',
            'excerpt_sw' => 'Huduma ya uwakala wa HaloPesa na Lipa Namba kiganjani mwako ukiwa na TIN, kitambulisho cha taifa, na namba ya Halotel.',
            'excerpt_en' => 'HaloPesa agency and Lipa number if you have a TIN, national ID, and a Halotel number.',
        ],
        [
            'date' => '2023-12-11',
            'image' => 'assets/images/vibe.jpg',
            'url' => 'https://www.instagram.com/p/C0vh7hkK_ZF/',
            'title_sw' => 'Karibu kwenye familia kubwa',
            'title_en' => 'Welcome to the big family',
            'excerpt_sw' => 'Uwakala wa HaloPesa, Lipa HaloPesa, AzamPesa, na Lipa Voda & Airtel. Kuwa wa tofauti ukiwa nasi.',
            'excerpt_en' => 'HaloPesa agency, HaloPesa Lipa, AzamPesa, and Voda & Airtel Lipa. Be different with us.',
        ],
    ],

    'gallery' => [
        ['src' => 'assets/images/hero-lipa.jpg', 'alt' => 'Pata Lipa Namba rahisi — Pedima Enterprises', 'href' => 'https://www.instagram.com/p/DOmK5C3je-h/'],
        ['src' => 'assets/images/team-halopesa.jpg', 'alt' => 'Timu ya Pedima katika shati za PEDIMA', 'href' => 'https://www.instagram.com/p/DJ_oribMtZH/'],
        ['src' => 'assets/images/offer-halopesa.jpg', 'alt' => 'HaloPesa Lipa Namba na uwakala bure', 'href' => 'https://www.instagram.com/p/DIiwoH2MWWQ/'],
        ['src' => 'assets/images/vibe.jpg', 'alt' => 'Huduma za Pedima Enterprises — AzamPesa, HaloPesa, Voda na Airtel', 'href' => 'https://www.instagram.com/p/C0vh7hkK_ZF/'],
        ['src' => 'assets/images/points.jpg', 'alt' => 'Points za HaloPesa', 'href' => 'https://www.instagram.com/p/C2b0RkMM_ZV/'],
        ['src' => 'assets/images/baraka.jpg', 'alt' => 'Kila siku mpya inakuja na baraka zake', 'href' => 'https://www.instagram.com/p/C2ZSe_CKM_8/'],
    ],
];
